<a href="https://colab.research.google.com/github/nimishwork6699/Deep_Learning_Project/blob/main/pytorch_simpleNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

class Model(nn.Module): #it inherit the class from the modulle of nn

 def __init__(self,num_features):

  super().__init__()
  self.linear=nn.Linear(num_features,1)#(input,output)
  self.sigmoid=nn.Sigmoid()

 def forward(self,features):
  out=self.linear(features)
  out=self.sigmoid(out)

  return out

In [4]:
# creating dataset
features=torch.rand(10,5)

# creating model
model=Model(features.shape[1]) #column wala

# call model for forward pass
 # we can do like
 # model.forward(features)--> but wont
model(features)

tensor([[0.5720],
        [0.5084],
        [0.4567],
        [0.5787],
        [0.5773],
        [0.5636],
        [0.5686],
        [0.4844],
        [0.5620],
        [0.4637]], grad_fn=<SigmoidBackward0>)

In [6]:
# showing model weights
model.linear.weight
#model.linear.bias

Parameter containing:
tensor([[-0.0616, -0.4277, -0.0357,  0.4155, -0.3829]], requires_grad=True)

In [8]:
!pip install torchinfo

In [9]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# For HIDDEN LAYER

In [10]:
class Model(nn.Module): #it inherit the class from the modulle of nn

 def __init__(self,num_features):

  super().__init__()
  self.linear1=nn.Linear(num_features,3)#(input,output)
  self.relu=nn.ReLU()
  self.linear2=nn.Linear(3,1)
  self.sigmoid=nn.Sigmoid()

 def forward(self,features):
  out=self.linear1(features)
  out=self.relu(out)
  out=self.linear2(out)
  out=self.sigmoid(out)

  return out

In [11]:
# creating dataset
features=torch.rand(10,5)

# creating model
model=Model(features.shape[1]) #column wala

# call model for forward pass
 # we can do like
 # model.forward(features)--> but wont
model(features)

tensor([[0.4137],
        [0.4160],
        [0.4110],
        [0.4157],
        [0.4110],
        [0.4249],
        [0.4108],
        [0.4201],
        [0.4180],
        [0.4066]], grad_fn=<SigmoidBackward0>)

In [12]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# USING SEQUENTIAL

In [14]:
class Model(nn.Module): #it inherit the class from the modulle of nn

 def __init__(self,num_features):

  super().__init__()
  self.network=nn.Sequential(
  nn.Linear(num_features,3),#(input,output)
  nn.ReLU(),
  nn.Linear(3,1),
  nn.Sigmoid()
  )
 def forward(self,features):
  out=self.network(features)

  return out